on:
  push:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          sudo ./Main.sh volteer Image.img
          tsshlink=$(curl --upload-file ./Image.img https://transfer.sh/ChromeOS.img)
          echo "REL_LINK=$tsshlink" >> $GITHUB_ENV
      - name: Cleaning
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: Stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.REL_LINK }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "Stable"
