on:
  push:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Building
      shell: bash
      run: |
        echo Build
        bash Main.sh volteer ChromeOS.img
  Clean:
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: Stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Upload:
    runs-on: ubuntu-latest
    needs: ["Build", "Clean"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "Stable"
        body: ${{ env.UPLOADURL }}
        token: ${{ secrets.GITHUB_TOKEN }}
