on:
  push:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Building
      shell: bash
      run: |
        echo Build
        bash Main.sh volteer ChromeOS.img
  Upload:
    runs-on: ubuntu-latest
    needs: ["Build"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        body: ${{ env.outf }}
        token: ${{ secrets.GITHUB_TOKEN }}
